spring.mongodb.uri=mongodb+srv://23070511_db_user:krEXF6NboRVoIPvD@cluster0.waparmh.mongodb.net/journaldb?retryWrites=true&w=majority
spring.data.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true
logging.level.org.springframework.security=DEBUG